### ISSUE TITLE
Adding GTK4 IM modules to support IME frameworks in Wayland

### ISSUE THREAD

**Issue by tinywrkb** [flathub/com.google.Chrome#106]
This should be fixed ​in the runtime, but a proof-of-concept, I created an extension that adds the IM modules to test this [new feature](https://bugs.chromium.org/p/chromium/issues/detail?id=1183262).

You would need first to build and install the [base app](https://github.com/tinywrkb/flathub/blob/org.freedesktop.Platform.IMModules/org.freedesktop.Platform.IMModules.BaseApp.yaml), as the extension need to be mounted somewhere during build time.  
And then you can build [the extension](https://github.com/tinywrkb/flathub/blob/org.freedesktop.Platform.IMModules/org.freedesktop.Platform.IMModules.yaml).  
Only Fcitx5 modules were added. Maybe I'll try adding IBus later.

Changes needed to the app:

* Create a mount point at `/app/immodules`
* Set `--env=GTK_PATH=/app/lib/gtkmodules:/app/immodules` in the `finish-args` array
* Add the extension
```
add-extensions:
  org.freedesktop.Platform.IMModules:
    directory: immodules
    version: '21.08'
    add-ld-path: lib
    no-autodownload: true
    autodelete: false
```

Chrome should be started with the flag `--gtk-version=4`
