### ISSUE TITLE
QT Theme

### ISSUE THREAD

**Issue by LinusDierheimer** [flathub/com.google.Chrome#217]
Since version 108, Chrome allows to use QT as an alternative theme provider to GTK: https://bugs.chromium.org/p/chromium/issues/detail?id=1317782. You might still need to pass the flag `--enable-features=AllowQt` tho.

On native chrome, this does work really well. On flatpak, clicking the `Use QT` button under `Settings -> Theme` does nothing. There is no usefull log, but strace shows that it is trying to dlopen a lot of qt libs that are missing from the flatpak.

I think QT should be shipped with the flatpak too, because it integrates much better with the KDE Plasma desktop, which is widley used.

**Comment by jh-devv** [comment]
+1

**Comment by jh-devv** [comment]
This could also fix this:
![Screenshot_20230921_150542](https://github.com/flathub/com.google.Chrome/assets/122896463/9a1ef924-3cfb-4c1e-b654-fca304c0cf9b)

**Comment by ssleert** [comment]
+1

**Comment by LinusDierheimer** [comment]
Update: `--enable-features=AllowQt` is no longer needed, QT is enabled by default now, and chrome even prefers QT on KDE by default now. So this is even more important.

**Comment by Bohne13** [comment]
> Update: `--enable-features=AllowQt` is no longer needed, QT is enabled by default now, and chrome even prefers QT on KDE by default now. So this is even more important.

So this bug report should be closed?

**Comment by Moe1369** [comment]
This is still an unresolved issue.  How can this be fixed?

**Comment by fatmalama** [comment]
still a thing.

**Comment by neronguyen** [comment]
+1

**Comment by LinusDierheimer** [comment]
I took the time and tried to implement it. Adding the required QT libs for chrome to use QT Theming is pretty simple:
```yaml
- name: qt6-base
  buildsystem: cmake-ninja
  builddir: true
  config-opts:
    - -DCMAKE_BUILD_TYPE=RelWithDebInfo
    - -DINSTALL_ARCHDATADIR=lib/qt6
    - -DQT_DISABLE_RPATH=ON
    - -DBUILD_WITH_PCH=FALSE
    - -DQT_FEATURE_glibc_fortify_source=OFF # The SDK already defines _FORTIFY_SOURCE=3, suppress warnings about redefinition
    - -DQT_FEATURE_concurrent=OFF   # libQtConcurrent.so
    - -DQT_FEATURE_eglfs=OFF        # libQt6EglFS*.so, plugins/egldeviceintegrations/, plugins/platforms/libqeglfs.so
    - -DQT_FEATURE_evdev=OFF        # plugins/generic/libqevdev*.so
    - -DQT_FEATURE_linuxfb=OFF      # plugins/platforms/libqlinuxfb.so
    - -DQT_FEATURE_network=OFF      # libQt6Network.so, plugins/networkinformation/, plugins/tls/, plugins/platforms/libqvnc.so
    - -DQT_FEATURE_printsupport=OFF # libQt6PrintSupport.so, plugins/printsupport/
    - -DQT_FEATURE_sql=OFF          # libQt6Sql.so, plugins/sqldrivers/
    - -DQT_FEATURE_testlib=OFF      # libQt6Test.so
    - -DQT_FEATURE_vkkhrdisplay=OFF # plugins/platforms/libqvkkhrdisplay.so
    - -DQT_FEATURE_xml=OFF          # libQt6Xml.so
  post-install:
    - cp ${FLATPAK_BUILDER_BUILDDIR}/LICENSES/* ${FLATPAK_DEST}/share/licenses/${FLATPAK_ID}/qt6-base/
  cleanup:
    - '*.a'
    - '*.prl'
    - /bin
    - /doc
    - /include
    - /lib/cmake
    - /lib/pkgconfig
    - /lib/qt6/libexec
    - /lib/qt6/metatypes
    - /lib/qt6/modules
    - /lib/qt6/sbom
    - /mkspecs
    - /share/qt6
  sources:
    - type: archive
      url: https://download.qt.io/official_releases/qt/6.11/6.11.1/submodules/qtbase-everywhere-src-6.11.1.tar.xz
      sha256: d9594a31228aa23ad6b531719a29b45f0f3989fe6c136d45767ea179f233c1ac
      x-checker-data:
        type: anitya
        project-id: 7927
        stable-only: true
        url-template: https://download.qt.io/official_releases/qt/$major.$minor/$version/submodules/qtbase-everywhere-src-$version.tar.xz
```
However, this still does not provide a native like experience on KDE plasma. The color scheme is used, but the title bar and controls look like an unstyled QT application. This is because KDE installs its own platformtheme plugin (`KDEPlasmaPlatformTheme6.so`, from [plasma-integration](https://invent.kde.org/plasma/plasma-integration)). Adding it to the flatpak is not a simple task, as it depends on like the whole KDE ecosystem.

What does work is switching the runtime from `org.freedesktop.platform` to `org.kde.platform`, which includes KDEs platform theme with all required dependencies. I am not sure however if the maintainers are willing to do this step, as it increases the install size notably, while only benefiting some users.
